Adicionando autor
NadiaaOliverr/e-Digi-Fundamentos pull request #1
Opened 2020-06-02 16:51 UTC by NadiaaOliverr

Primeiro card

2020-06-02 17:05 UTC, wandersonmaceds requested changes

2020-06-02 17:05 UTC, wandersonmaceds commented on helpers/decorators.py
> +def validate_field(function):
Aqui o validate_fiel é um nome muito genérico e não diz muito sobre o que ele faz quando você usa o decorator. Decorators devem ser expressivos e indicarem de forma mais clara possível o seu papel, casos de validação é comum ver nomes como `@is_not_null`, `@is_not_empty` ou `@is_email` e coisas assim. `@validate_field` não diz nada sobre que tipo de validação está sendo aplicada.

2020-06-02 17:05 UTC, wandersonmaceds commented on model/author.py
> +    @validate_field
Viu? Se olhar bem, daqui a x tempo, você não vai ter a mínima ideia do que validate_field quer dizer.

2020-06-02 17:05 UTC, wandersonmaceds commented on model/author.py
> +    @validate_field
Não é que precise saber o que está acontecendo por baixo dos panos, mas a expressividade do código, precisa te passar pelo menos uma pista.

2020-06-02 17:14 UTC, NadiaaOliverr commented on helpers/decorators.py
> +def validate_field(function):
Faz muito sentido.

2020-06-02 17:15 UTC, NadiaaOliverr commented on helpers/decorators.py
> +def validate_field(function):
Nesse caso, convém eu separar um único decorator que valida se o nome é vazio ou se ele é None em dois?

2020-06-02 18:21 UTC, wandersonmaceds commented on helpers/decorators.py
> +def validate_field(function):
Acho que você pode considerar os `is_not_null` que também vê por baixo dos panos se não é vazio. É o mais direto a se fazer no momento, mas pode acontecer sim de você ter os 3: `is_not_null`, `is_not_empty` e `is_not_null_or_empty`.

2020-06-03 11:35 UTC, wandersonmaceds approved these changes

2020-06-03 12:52 UTC, merged