Adicionando visualização dos livros
NadiaaOliverr/e-Digi-Fundamentos pull request #5
Opened 2020-06-05 21:45 UTC by NadiaaOliverr

Quarto card

2020-06-06 17:25 UTC, wandersonmaceds requested changes

2020-06-06 17:25 UTC, wandersonmaceds commented on dao/book_dao.py
> +    @is_not_null
Seu decorator sabe o que deve não ser nulo aqui neste contexto? Como?

2020-06-06 17:25 UTC, wandersonmaceds commented on controller/controller.py
> +class Controller:
Se eu posso fazer: 

```
book = Book()
dao = BookDAO()
dao.save(book)
bookfound = dao.find_by_title(title)
print(bookfound)
```

Por que eu precisaria desse Controller e dessa classe BookView? 
Aqui foram adicionadas duas camandas que geraram indireção no seu código original, eles não fazem nada mais que repassar chamadas de função. 

O código ficou mais complexo e não trouxe um benefício perceptível.

2020-06-06 18:38 UTC, NadiaaOliverr commented on controller/controller.py
> +class Controller:
Acho que foi prematuro mesmo, concordo com você. Queria separar melhor e adicionei algo desnecessário no momento. Vou modificar.

2020-06-06 18:47 UTC, NadiaaOliverr commented on dao/book_dao.py
> +    @is_not_null
Sabe =)  No caso o título não deve ser nulo. Para validar isso ele pegará como referência o segundo parâmetro da função na qual ele está decorando(o primeiro é o objeto em si(self)).

2020-06-08 12:02 UTC, wandersonmaceds approved these changes

2020-06-08 12:18 UTC, merged