Adicionando testes de unidade em toda aplicação
NadiaaOliverr/e-Digi-Fundamentos pull request #7
Opened 2020-06-22 04:43 UTC by NadiaaOliverr

Sexto card

2020-06-22 05:12 UTC, NadiaaOliverr commented
@wandersonmaceds , em todos os erros eu explodo no ```raise``` uma exceção do tipo Exception, entretanto, estou achando genérico demais. Observe que nos meus testes eu só capturo Exception(que é a mãe de todos os outros tipos de exceções). Acha viável modelar essas exceções para algo mais específico?

2020-06-22 17:38 UTC, wandersonmaceds requested changes
Testes servem para garatir o funcionamento do sistema, ou seja, o que é esperado tanto de sucesso quanto de falha, se você testar só as falhas, como você garante que os sucessos não são falsos positivos?

Sobre a especificidade da exception, você pode fazer uso sim, em linguagens mais tradicionais, um parâmetro inválido pode ser representado pela classe IllegalArgumentException por exemplo, eventos sem previsibilidade, que acontecem em tempo de execução, podem ser representadas pela RuntimeException e por ai vai. Se o Python tem algo assim, fazer uso, deixa seu código mais expressívo.

2020-06-22 17:38 UTC, wandersonmaceds commented on tests/test_author.py
> +class TestAuthor(unittest.TestCase):
Só existe teste que garante os erros? E os caminhos felizes, como você garante que ele funciona?

2020-06-22 18:04 UTC, NadiaaOliverr commented on tests/test_author.py
> +class TestAuthor(unittest.TestCase):
Bem, os caminhos felizes estão no arquivo main.py que é o principal, mas entendi a ideia, vou colocá-los aí também.

2020-06-22 18:07 UTC, NadiaaOliverr commented on tests/test_author.py
> +class TestAuthor(unittest.TestCase):
> Sobre a especificidade da exception, você pode fazer uso sim, em linguagens mais tradicionais, um parâmetro inválido pode ser representado pela classe IllegalArgumentException por exemplo, eventos sem previsibilidade, que acontecem em tempo de execução, podem ser representadas pela RuntimeException e por ai vai. Se o Python tem algo assim, fazer uso, deixa seu código mais expressívo.

Tem as exceções dele próprio como RuntimeError, TypeError, ValueError e por aí vai, vou escolher as que melhores se encaixam. E tem como personalizar também, como fiz daquela vez.

2020-06-29 12:23 UTC, NadiaaOliverr commented
Preciso corrigir/melhorar alguma coisa?

2020-06-30 00:11 UTC, wandersonmaceds requested changes
Não comentei em todos os lugares, algumas questões se repetem. Dá uma olhada se faz sentido, desculpa a demora.

2020-06-30 00:11 UTC, wandersonmaceds commented on dao/author_dao.py
> +            raise TypeError('O argumento passado não é do tipo Autor')
Aqui preciso confessar pra você que acho que a gente pode fazer melhor, vou sugerir você pesquisar e ler sobre `early return`, por que você pode reduzir essa coisa de if dentro de if só usando esse conceito. Isso repete em vários lugares. A tendência é que toda vez que você precise executar mais alguma coisa com base em uma condição, você tenha uma cadeia de if dentro de if e if e if com vários elses voltando.

2020-06-30 00:11 UTC, wandersonmaceds commented on tests/test_book.py
> +                edition="1254", price=120.56):
Boa sacada! :D

2020-06-30 00:11 UTC, wandersonmaceds commented on tests/test_book.py
> +            self._setup(title='   ')
Aqui eu me pergunto se não são testes equivalentes, todos eles lançam o mesmo erro mudando apenas o tipo de entrada, eu costumo pensar que deveria ser um único teste com vários asserts.

2020-06-30 00:11 UTC, wandersonmaceds commented on tests/test_book.py
> +        dao = BookDao()
Acho uma boa ideia você separar o teste do dao do seu teste do próprio livro.

2020-06-30 00:11 UTC, wandersonmaceds commented on tests/test_sale.py
> +        BookDao.list_book = []
O list_book ficou público só para o teste passar?

2020-07-01 16:55 UTC, NadiaaOliverr commented on app/model/book.py
> +        self.__set_category(category)
Percebi que eu estava aceitando o autor e a categoria que o usuário me passava quando instanciava um livro, mas eu não conferia se esse autor e essa categoria existia no "banco" ou não, eu literalmente só aceita.

2020-07-01 16:57 UTC, NadiaaOliverr commented
Modifiquei a estrutura das pastas e dos imports porque da forma como estava, o design estava muito propício a importações circulações, devido a forma como o Python irá carregar os arquivos que estavam sendo exportados no ```__all__```

2020-07-01 17:06 UTC, NadiaaOliverr commented on tests/test_sale.py
> +        BookDao.list_book = []
Não. Em todos os outros databases em outro momento(outras branchs) eu tratava o atributo estático como público também, mas havia esquecido desse

2020-07-02 13:49 UTC, wandersonmaceds requested changes

2020-07-02 13:49 UTC, wandersonmaceds commented on app/dao/author_dao.py
> +        return author
Não é curioso que você especifique o retorno com string mas na verdade retorne um autor?

2020-07-02 13:49 UTC, wandersonmaceds commented on app/model/sale.py
> +    def quantity_sale(self) -> int:
Perguntinha: Por que um método se chama quantity_sale e o outro se chama title_book? Um parece estar bem alinhado com a ideia da venda e outra parece estar muito acoplada com a ideia de que o sale é um book.

2020-07-02 13:49 UTC, wandersonmaceds commented on app/tests/test_dao/test_author.py
> +        self.assertIsNone(dao.save(author_luciano))
Só isso pode te gerar falso positivo, sugiro buscar na lista do dao se o livro tá lá, também.

2020-07-02 13:49 UTC, wandersonmaceds commented on app/tests/test_dao/test_author.py
> +        self.assertIsNone(dao.save(author_luciano))
Vale pros demais testes parecidos.

2020-07-02 13:49 UTC, wandersonmaceds commented on app/tests/test_dao/test_author.py
> +        self.assertIsNone(dao.save(author_luciano))
Não ter erro é um passo que você assume para o sucesso da operação, mas você ainda precisa garantir que aconteceu o que deveria acontecer, justo por que, dessa forma, não seria muito diferente de fazer um self.assertTrue(true);

2020-07-02 13:53 UTC, NadiaaOliverr commented on app/dao/author_dao.py
> +        return author
Sim, o que conversamos ontem. Foi corrigido nos commits posteriores essa parte

2020-07-03 21:56 UTC, wandersonmaceds approved these changes

2020-07-04 01:35 UTC, merged